<a href="https://colab.research.google.com/github/mayank261193/Session-6-Pandas/blob/main/Session6_FollowAlong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 6 · Pandas Core
### Applied AI & Analytics Lab · Rebounce Careers

**Instructor:** Mr. Varunn Kaushik  **·**  **Duration:** ~2 hours  **·**  **Tool:** Google Colab

---

### What you'll learn today

1. Load a real CSV into a **DataFrame** and get oriented with `head`, `info`, `describe`
2. Select **columns**, and rows by label (`loc`) and position (`iloc`)
3. **Filter** rows with conditions
4. **Clean** data — missing values, duplicates, and messy text/types
5. **Group** and aggregate with `groupby`
6. **Merge** two tables into one
7. Run a small **end-to-end policy analysis**

### How to use this notebook

This is our **live class notebook** — I write each cell, you follow along in your own copy. Every concept follows the same pattern: **Concept → Example → Practice time → Solution**.

> **Setup:** upload `session6_policy_data.csv` and `session6_region_lookup.csv` using the folder icon on the left, then run the next cell.

In [52]:
import pandas as pd
print('pandas', pd.__version__)

pandas 2.2.3

---
## Section 1 · DataFrames & Loading

A **DataFrame** is a table: rows and **named columns**. It's the pandas version of a spreadsheet — or a NumPy array that finally has labels. A single column is a **Series**.

### 1.1 · Load a CSV

In [53]:
import pandas as pd


df = pd.read_csv("session6_policy_data.csv")

print("shape:", df.shape)
df.head()

shape: (51, 5)

    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
1    South  2021             88.7            15.2       62000
2     East  2021             91.2             9.8       48000
3     West  2021             85.4            11.1       53000
4  Central  2021             90.1            14.0       59000

### 1.2 · First look — head, tail, info, describe

In [54]:
df.head(3)          # first 3 rows

  region  year  employment_rate  budget_million  population
0  North  2021             92.3            12.5       50000
1  South  2021             88.7            15.2       62000
2   East  2021             91.2             9.8       48000

In [55]:
df.tail(3)          # last 3 rows

     region  year  employment_rate  budget_million  population
48     West  2030             91.5            15.5       57500
49  Central  2030             95.5            18.5       63500
50    North  2021             92.3            12.5       50000

In [56]:
df.info()           # column names, non-null counts, dtypes
# Notice: budget_million has fewer non-null values than the others — missing data.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region           51 non-null     object
 1   year             51 non-null     int64
 2   employment_rate  51 non-null     float64
 3   budget_million   49 non-null     float64
 4   population       51 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB

In [57]:
df.describe()       # mean, min, max etc. for the numeric columns

              year  employment_rate  budget_million    population
count    51.000000        51.000000       49.000000     51.000000
mean   2025.411765        92.100000       14.646939  56321.078431
std       2.940588         2.646205        2.469826   5943.875782
min    2021.000000        85.400000        9.800000  48000.000000
25%    2023.000000        90.650000       12.600000  51012.500000
50%    2025.000000        92.400000       14.500000  55000.000000
75%    2028.000000        93.950000       16.500000  62000.000000
max    2030.000000        97.000000       19.500000  67400.000000

### 1.3 · A column is a Series

In [58]:
regions = df[["region", "employment_rate"]]
print(regions.head())
print(regions.tail())
regions.describe()

    region  employment_rate
0    North             92.3
1    South             88.7
2     East             91.2
3     West             85.4
4  Central             90.1
     region  employment_rate
46    South             94.5
47     East             94.8
48     West             91.5
49  Central             95.5
50    North             92.3

       employment_rate
count        51.000000
mean         92.100000
std           2.646205
min          85.400000
25%          90.650000
50%          92.400000
75%          93.950000
max          97.000000

In [59]:
df[["region", "employment_rate"]]

     region  employment_rate
0     North             92.3
1     South             88.7
2      East             91.2
3      West             85.4
4   Central             90.1
5     North             92.8
6     South             89.3
7      East             91.6
8      West             86.1
9   Central             90.7
10   north              93.3
11    South             90.0
12     East             92.0
13     West             86.8
14  Central             91.3
15    North             93.9
16    South             90.6
17     East             92.4
18     West             87.4
19  Central             91.9
20    North             94.4
21    South             91.3
22     East             92.8
23     West             88.1
24  Central             92.5
25    North             94.9
26    South             91.9
27     East             93.2
28     West             88.8
29  Central             93.1
30    North             95.4
31    South             92.5
32     East             93.6
33     West             89.5
34  Central             93.7
35    North             95.9
36    South             93.2
37     East             94.0
38     West             90.2
39  Central             94.3
40    North             96.5
41    South             93.8
42     East             94.4
43     West             90.8
44  Central             94.9
45    North             97.0
46    South             94.5
47     East             94.8
48     West             91.5
49  Central             95.5
50    North             92.3

### ✍️ Practice time — get oriented

Load the file again into a variable called `policy`. Print its shape, and print how many **non-null** `budget_million` values it has (hint: `.info()` shows this, or `policy['budget_million'].notna().sum()`).

In [60]:
# YOUR CODE HERE

**Solution:**

In [61]:
policy = pd.read_csv("session6_policy_data.csv")
print(policy.shape)                              # (51, 5)
print(policy["budget_million"].notna().sum())   # 49 present -> 2 missing

(51, 5)
49

---
## Section 2 · Selecting — columns, `loc` and `iloc`

- `df["col"]` → one column (a Series).  `df[["a", "b"]]` → several columns (a DataFrame).
- `df.loc[...]` selects by **label** (row index / column name).
- `df.iloc[...]` selects by **position** (0-based numbers), exactly like NumPy.

### 2.1 · Select columns

In [62]:
df[["region", "employment_rate"]].head()

    region  employment_rate
0    North             92.3
1    South             88.7
2     East             91.2
3     West             85.4
4  Central             90.1

### 2.2 · loc — by label

In [63]:
df = pd.read_csv("session6_policy_data.csv")
print(df.loc[0])                       # the whole first row (by index label 0)
print(df.loc[0, "employment_rate"])    # one value: 92.3

region             North
year                2021
employment_rate     92.3
budget_million      12.5
population         50000
Name: 0, dtype: object
92.3

### 2.3 · iloc — by position

In [64]:
print(df.iloc[0:3, 0:3])       # row 0, column 2 -> 92.3 (employment_rate)

  region  year  employment_rate
0  North  2021             92.3
1  South  2021             88.7
2   East  2021             91.2

### ✍️ Practice time — selecting

From `df`, print (1) the `population` column's first 5 values, and (2) the value at row **4**, column `budget_million` using **iloc**.

In [65]:
# YOUR CODE HERE

**Solution:**

In [66]:
#[0:3]= 0, 1, 2

In [67]:
#print(df["population"].head())
print(df.head())

print(df.iloc[4, 3])       # row 4, column 3 (budget_million)

    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
1    South  2021             88.7            15.2       62000
2     East  2021             91.2             9.8       48000
3     West  2021             85.4            11.1       53000
4  Central  2021             90.1            14.0       59000
14.0

---
## Section 3 · Filtering rows

Same idea as a NumPy boolean mask, but the mask is built from a **column**. `df[df["col"] > value]` keeps only the rows where the condition is True.

### 3.1 · One condition

In [68]:
high = df[df["employment_rate"] > 92]

print(high.shape)

high.head()

(28, 5)

    region  year  employment_rate  budget_million  population
0    North  2021             92.3            12.5       50000
5    North  2022             92.8            13.0       50225
10  north   2023             93.3            13.5       50450
15   North  2024             93.9            14.0       50675
17    East  2024             92.4            11.2       49350

### 3.2 · Two conditions — use `&` (and) / `|` (or), each side in ( )

In [69]:
recent_high = df[(df["employment_rate"] > 92) & (df["year"] >= 2027)]
recent_high[["region", "year", "employment_rate"]].head()

     region  year  employment_rate
30    North  2027             95.4
31    South  2027             92.5
32     East  2027             93.6
34  Central  2027             93.7
35    North  2028             95.9

### ✍️ Practice time — filtering

Keep only the rows where `population` is greater than 60000. How many rows is that?

In [70]:
# YOUR CODE HERE

**Solution:**

In [71]:
big = df[df["population"] > 60000]
print(big)
print(big.shape[0], "rows")
big[["region", "year", "population"]].head()

     region  year  employment_rate  budget_million  population
1     South  2021             88.7            15.2       62000
6     South  2022             89.3             NaN       62600
11    South  2023             90.0            16.2       63200
16    South  2024             90.6            16.6       63800
19  Central  2024             91.9            15.5       60500
21    South  2025             91.3            17.1       64400
24  Central  2025             92.5            16.0       61000
26    South  2026             91.9            17.6       65000
29  Central  2026             93.1            16.5       61500
31    South  2027             92.5            18.1       65600
34  Central  2027             93.7            17.0       62000
36    South  2028             93.2            18.6       66200
39  Central  2028             94.3            17.5       62500
41    South  2029             93.8            19.0       66800
44  Central  2029             94.9            18.0       63000
46    South  2030             94.5            19.5       67400
49  Central  2030             95.5            18.5       63500
17 rows

     region  year  population
1     South  2021       62000
6     South  2022       62600
11    South  2023       63200
16    South  2024       63800
19  Central  2024       60500

---
## Section 4 · Cleaning — missing values, duplicates & messy text

Real data is messy. This file has three problems on purpose: **missing budgets**, a **duplicate row**, and a **mis-typed region label**. We fix each in code.

### 4.1 · Missing values

In [72]:
df.isna().sum()

region             0
year               0
employment_rate    0
budget_million     2
population         0
dtype: int64

In [73]:
print(df.isna().sum())                       # missing count per column

mean_budget = df["budget_million"].mean()


# print("mean budget:", round(mean_budget, 2))

region             0
year               0
employment_rate    0
budget_million     2
population         0
dtype: int64

In [74]:
df_clean = df.copy()

df_clean["budget_million"] = df_clean["budget_million"].fillna(mean_budget)

print(df_clean["budget_million"].isna().sum())   # 0 -> all filled

print(df_clean)

0
     region  year  employment_rate  budget_million  population
0     North  2021             92.3       12.500000       50000
1     South  2021             88.7       15.200000       62000
2      East  2021             91.2        9.800000       48000
3      West  2021             85.4       11.100000       53000
4   Central  2021             90.1       14.000000       59000
5     North  2022             92.8       13.000000       50225
6     South  2022             89.3       14.646939       62600
7      East  2022             91.6       10.300000       48450
8      West  2022             86.1       11.600000       53500
9   Central  2022             90.7       14.500000       59500
10   north   2023             93.3       13.500000       50450
11    South  2023             90.0       16.200000       63200
12     East  2023             92.0       10.700000       48900
13     West  2023             86.8       12.100000       54000
14  Central  2023             91.3       15.000000       60000
15    North  2024             93.9       14.000000       50675
16    South  2024             90.6       16.600000       63800
17     East  2024             92.4       11.200000       49350
18     West  2024             87.4       12.600000       54500
19  Central  2024             91.9       15.500000       60500
20    North  2025             94.4       14.500000       50900
21    South  2025             91.3       17.100000       64400
22     East  2025             92.8       11.700000       49800
23     West  2025             88.1       13.100000       55000
24  Central  2025             92.5       16.000000       61000
25    North  2026             94.9       14.646939       51125
26    South  2026             91.9       17.600000       65000
27     East  2026             93.2       12.200000       50250
28     West  2026             88.8       13.600000       55500
29  Central  2026             93.1       16.500000       61500
30    North  2027             95.4       15.500000       51350
31    South  2027             92.5       18.100000       65600
32     East  2027             93.6       12.600000       50700
33     West  2027             89.5       14.000000       56000
34  Central  2027             93.7       17.000000       62000
35    North  2028             95.9       16.000000       51575
36    South  2028             93.2       18.600000       66200
37     East  2028             94.0       13.100000       51150
38     West  2028             90.2       14.500000       56500
39  Central  2028             94.3       17.500000       62500
40    North  2029             96.5       16.500000       51800
41    South  2029             93.8       19.000000       66800
42     East  2029             94.4       13.600000       51600
43     West  2029             90.8       15.000000       57000
44  Central  2029             94.9       18.000000       63000
45    North  2030             97.0       17.000000       52025
46    South  2030             94.5       19.500000       67400
47     East  2030             94.8       14.000000       52050
48     West  2030             91.5       15.500000       57500
49  Central  2030             95.5       18.500000       63500
50    North  2021             92.3       12.500000       50000

### 4.2 · Duplicate rows

In [75]:
print("duplicates:", df_clean.duplicated().sum())   # 1
df_clean = df_clean.drop_duplicates()
print("after drop:", df_clean.shape)                # one row fewer

duplicates: 1
after drop: (50, 5)

### 4.3 · Messy text — clean the region labels

In [76]:
print(df_clean["region"].unique())   # notice a stray 'north ' with wrong case/space

df_clean["region"] = df_clean["region"].str.strip().str.title()

print(df_clean["region"].unique())   # now exactly 5 clean labels

['North' 'South' 'East' 'West' 'Central' 'north ']
['North' 'South' 'East' 'West' 'Central']

### ✍️ Practice time — cleaning

On a **fresh** load of the data: fill the missing `budget_million` with the column **median** (not mean) this time, then report how many duplicate rows exist before you drop them.

In [77]:
# YOUR CODE HERE

**Solution:**

In [78]:
d = pd.read_csv("session6_policy_data.csv")
d["budget_million"] = d["budget_million"].fillna(d["budget_million"].median())
print("missing now:", d["budget_million"].isna().sum())   # 0
print("duplicates:", d.duplicated().sum())                # 1

missing now: 0
duplicates: 1

---
## Section 5 · GroupBy & Aggregate

`groupby` splits the table by a column, applies a calculation to each group, and combines the results. This is the single most useful analysis move in pandas.

### 5.1 · Average by region

In [79]:
avg_emp = df_clean.groupby("region")["employment_rate"].mean().sort_values(ascending=False)
print(avg_emp)

region
North      94.64
East       93.00
Central    92.80
South      91.58
West       88.46
Name: employment_rate, dtype: float64

### 5.2 · Several aggregations at once with `.agg`

In [80]:
summary = df_clean.groupby("region").agg(
    avg_employment=("employment_rate", "mean"),
    total_population=("population", "sum"),
    years=("year", "count"),
).reset_index()
summary

    region  avg_employment  total_population  years
0  Central           92.80            612500     10
1     East           93.00            500250     10
2    North           94.64            510125     10
3    South           91.58            647000     10
4     West           88.46            552500     10

### ✍️ Practice time — groupby

Using `df_clean`, find the **average `budget_million` per region**, sorted highest first.

In [81]:
# YOUR CODE HERE

**Solution:**

In [82]:
by_budget = df_clean.groupby("region")["budget_million"].mean().sort_values(ascending=False)
print(by_budget)

region
South      17.254694
Central    16.250000
North      14.714694
West       13.310000
East       11.920000
Name: budget_million, dtype: float64

---
## Section 6 · Merge / Join two tables

Real data is spread across files. `pd.merge` joins them on a shared **key** column. Here we attach each region's **zone** and **employment target** from a lookup table.

In [83]:
lookup = pd.read_csv("session6_region_lookup.csv")
lookup

    region    zone  target_employment
0    North  Zone-A               93.0
1    South  Zone-B               92.0
2     East  Zone-A               93.5
3     West  Zone-C               90.0
4  Central  Zone-B               93.0

### 6.1 · Left merge on `region`

In [84]:
merged = pd.merge(df_clean, lookup, on="region", how="left")
merged

merged[["region", "year", "employment_rate", "zone", "target_employment"]].head()

    region  year  employment_rate    zone  target_employment
0    North  2021             92.3  Zone-A               93.0
1    South  2021             88.7  Zone-B               92.0
2     East  2021             91.2  Zone-A               93.5
3     West  2021             85.4  Zone-C               90.0
4  Central  2021             90.1  Zone-B               93.0

> **Why `how="left"`?** It keeps every row of the left table (our policy data) and attaches lookup columns where the key matches. If a region were missing from the lookup, those columns would be `NaN` — visible, not silently dropped.

### ✍️ Practice time — merge

After merging, create a boolean column `above_target` that is `True` when `employment_rate` is at or above `target_employment`. Then print how many rows are above target.

In [85]:
# YOUR CODE HERE

**Solution:**

In [86]:
merged["above_target"] = merged["employment_rate"] >= merged["target_employment"]
merged
print(merged["above_target"].sum(), "rows at or above target")

24 rows at or above target

---
## Section 7 · Bringing It Together — a policy analysis

Load → clean → group → merge → insight. The same workflow an analyst runs on any real dataset.

In [87]:
# 1. load
data = pd.read_csv("session6_policy_data.csv")

# 2. clean
data["budget_million"] = data["budget_million"].fillna(data["budget_million"].mean())
data = data.drop_duplicates()
data["region"] = data["region"].str.strip().str.title()

# 3. merge in targets
data = pd.merge(data, pd.read_csv("session6_region_lookup.csv"), on="region", how="left")

# 4. per-region: average employment vs target
report = data.groupby("region").agg(
    avg_employment=("employment_rate", "mean"),
    target=("target_employment", "first"),
).reset_index()
report["meets_target"] = report["avg_employment"] >= report["target"]
report

    region  avg_employment  target  meets_target
0  Central           92.80    93.0         False
1     East           93.00    93.5         False
2    North           94.64    93.0          True
3    South           91.58    92.0         False
4     West           88.46    90.0         False

A policymaker can read that table in ten seconds: average employment per region, its target, and a clear yes/no on whether the region is meeting it.

---
## Section 8 · Mini Challenges

Try each on your own first — solutions follow each one.

### Challenge 1 · The 2030 snapshot
Filter `df_clean` to just the year **2030** and show region + employment_rate, highest first.

In [88]:
# YOUR CODE HERE
Clean=df_clean[df_clean["year"]==2030].sort_values("employment_rate",ascending=False)
Clean[["region","employment_rate"]]

     region  employment_rate
45    North             97.0
49  Central             95.5
47     East             94.8
46    South             94.5
48     West             91.5

**Solution:**

In [89]:
snap = df_clean[df_clean["year"] == 2030].sort_values("employment_rate", ascending=False)
snap[["region", "employment_rate"]]

     region  employment_rate
45    North             97.0
49  Central             95.5
47     East             94.8
46    South             94.5
48     West             91.5

### Challenge 2 · Biggest budget region
Which region has the highest **total** budget across all years?

In [90]:
# YOUR CODE HERE

**Solution:**

In [91]:
totals = df_clean.groupby("region")["budget_million"].sum()
print(totals.idxmax(), "->", round(totals.max(), 1))

South -> 172.5

### Challenge 3 · Growth check
For **North**, print employment_rate in 2021 and 2030, and the change between them.

In [92]:
# YOUR CODE HERE

**Solution:**

In [93]:
north = df_clean[df_clean["region"] == "North"]
start = north[north["year"] == 2021]["employment_rate"].iloc[0]
end   = north[north["year"] == 2030]["employment_rate"].iloc[0]
print(f"2021: {start}  2030: {end}  change: +{round(end - start, 1)}")

2021: 92.3  2030: 97.0  change: +4.7

---
## Session summary

In two hours you:

- ✅ Loaded a real CSV into a **DataFrame** and explored it with `head`/`info`/`describe`
- ✅ Selected columns and rows with `loc` and `iloc`
- ✅ **Filtered** rows with conditions
- ✅ **Cleaned** missing values, duplicates and messy text
- ✅ **Grouped** and **merged** to answer real questions

You can now take a messy file and turn it into a clean, joined, summarised table — the core of every analytics job.

### Homework

1. Finish the practice notebooks (Q1–Q3) and push them to your GitHub Session-6 folder
2. **Start Minor Project 3 (Pandas 301)** — the data-wrangling project. It's due at the end of Weekend 3
3. Re-run Section 7 on a dataset you care about, if you brought one

### Next up — Session 7

**Visualisation & Data Acquisition** — turn these clean tables into charts, and pull data from APIs and the web.

---
*Rebounce Careers · Applied AI & Analytics Lab · Session 6*